### ISSUE TITLE
Error on step 3.6 Sanity-check pipeline

### ISSUE THREAD

**Issue by javipolo** [rh-aiservices-bu/insurance-claim-processing#213]
**Describe the bug**
When following the demo, in 3.6, the `sanity-check` pipeline fails in the `test_security` step number 3

**To Reproduce**
Follow the demo until the step 3.6

**Expected behavior**
Pipeline runs properly

**Screenshots**
![image](https://github.com/rh-aiservices-bu/insurance-claim-processing/assets/1888961/4067f0c9-bbfb-45d9-8a84-9e6b8f8d27de)

**Relevant logs**
Looking at the logs of `test_security`, I think the relevant part is:
```
[I 09:28:21.821] 'sanity_check':'test_security' - downloaded test_security-6b595dc7-afb8-46bb-bf52-7cd695ddafb8.tar.gz from bucket: user1, object: sanity_check-0531092802/test_security-6b595dc7-afb8-46bb-bf52-7cd695ddafb8.tar.gz (0.019 secs)
tar: Removing leading `/' from member names
/
test_security.py
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
```

**Full log output**
However, here I provide the full log output of `test_security`:
```
Downloading file:///opt/app-root/bin/utils/bootstrapper.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31480  100 31480    0     0  30.0M      0 --:--:-- --:--:-- --:--:-- 30.0M
Downloading file:///opt/app-root/bin/utils/requirements-elyra.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1462  100  1462    0     0  1427k      0 --:--:-- --:--:-- --:--:-- 1427k
Requirement already satisfied: packaging in /opt/app-root/lib/python3.9/site-packages (23.1)

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
[D 09:28:08.809] Parsing Arguments.....
[I 09:28:08.811] 'sanity_check':'test_security' - starting operation 
[I 09:28:08.811] 'sanity_check':'test_security' - Installing packages 
[I 09:28:08.811] Package not found. Installing ipykernel package with version 6.13.0...
[I 09:28:08.811] Package not found. Installing ipython package with version 8.10.0...
[I 09:28:08.811] Package not found. Installing ipython-genutils package with version 0.2.0...
[I 09:28:08.811] Package not found. Installing jinja2 package with version 3.0.3...
[I 09:28:08.811] Package not found. Installing jupyter-client package with version 7.3.1...
[I 09:28:08.811] Package not found. Installing jupyter-core package with version 4.11.2...
[I 09:28:08.811] Package not found. Installing MarkupSafe package with version 2.1.1...
[I 09:28:08.811] Package not found. Installing minio package with version 7.1.15...
[I 09:28:08.811] Package not found. Installing nbclient package with version 0.6.3...
[I 09:28:08.811] Package not found. Installing nbconvert package with version 6.5.1...
[I 09:28:08.811] Package not found. Installing nbformat package with version 5.4.0...
[I 09:28:08.811] Package not found. Installing papermill package with version 2.3.4...
[I 09:28:08.811] Package not found. Installing pyzmq package with version 24.0.1...
[I 09:28:08.811] Package not found. Installing prompt-toolkit package with version 3.0.30...
[I 09:28:08.811] Package not found. Installing requests package with version 2.31.0...
[I 09:28:08.811] Package not found. Installing tornado package with version 6.3.3...
[I 09:28:08.811] Package not found. Installing traitlets package with version 5.1.1...
[I 09:28:08.811] Package not found. Installing urllib3 package with version 1.26.9...
Collecting ipykernel==6.13.0
  Downloading ipykernel-6.13.0-py3-none-any.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 4.7 MB/s eta 0:00:00
Collecting ipython==8.10.0
  Downloading ipython-8.10.0-py3-none-any.whl (784 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 784.3/784.3 kB 31.6 MB/s eta 0:00:00
Collecting ipython-genutils==0.2.0
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting jinja2==3.0.3
  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 kB 278.5 MB/s eta 0:00:00
Collecting jupyter-client==7.3.1
  Downloading jupyter_client-7.3.1-py3-none-any.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.0/131.0 kB 305.2 MB/s eta 0:00:00
Collecting jupyter-core==4.11.2
  Downloading jupyter_core-4.11.2-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 284.1 MB/s eta 0:00:00
Collecting MarkupSafe==2.1.1
  Downloading MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting minio==7.1.15
  Downloading minio-7.1.15-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 234.0 MB/s eta 0:00:00
Collecting nbclient==0.6.3
  Downloading nbclient-0.6.3-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 281.1 MB/s eta 0:00:00
Collecting nbconvert==6.5.1
  Downloading nbconvert-6.5.1-py3-none-any.whl (563 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 563.8/563.8 kB 319.3 MB/s eta 0:00:00
Collecting nbformat==5.4.0
  Downloading nbformat-5.4.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.3/73.3 kB 264.1 MB/s eta 0:00:00
Collecting papermill==2.3.4
  Downloading papermill-2.3.4-py3-none-any.whl (37 kB)
Collecting pyzmq==24.0.1
  Downloading pyzmq-24.0.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 313.8 MB/s eta 0:00:00
Collecting prompt-toolkit==3.0.30
  Downloading prompt_toolkit-3.0.30-py3-none-any.whl (381 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 332.5 MB/s eta 0:00:00
Collecting requests==2.31.0
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 198.3 MB/s eta 0:00:00
Collecting tornado==6.3.3
  Downloading tornado-6.3.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.7/427.7 kB 326.8 MB/s eta 0:00:00
Collecting traitlets==5.1.1
  Downloading traitlets-5.1.1-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.0/102.0 kB 300.4 MB/s eta 0:00:00
Collecting urllib3==1.26.9
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 kB 313.6 MB/s eta 0:00:00
Requirement already satisfied: packaging in /opt/app-root/lib/python3.9/site-packages (from ipykernel==6.13.0) (23.1)
Collecting nest-asyncio
  Downloading nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
Collecting debugpy>=1.0
  Downloading debugpy-1.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 234.6 MB/s eta 0:00:00
Collecting psutil
  Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 318.0 MB/s eta 0:00:00
Collecting matplotlib-inline>=0.1
  Downloading matplotlib_inline-0.1.7-py3-none-any.whl (9.9 kB)
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pexpect>4.3
  Downloading pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 269.8 MB/s eta 0:00:00
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting stack-data
  Downloading stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting jedi>=0.16
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 334.8 MB/s eta 0:00:00
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting pygments>=2.4.0
  Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 314.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/app-root/lib/python3.9/site-packages (from jupyter-client==7.3.1) (2.8.2)
Collecting entrypoints
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting certifi
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 303.5 MB/s eta 0:00:00
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Collecting bleach
  Downloading bleach-6.1.0-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.8/162.8 kB 262.0 MB/s eta 0:00:00
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.9/147.9 kB 310.1 MB/s eta 0:00:00
Collecting lxml
  Downloading lxml-5.2.2-cp39-cp39-manylinux_2_28_x86_64.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 210.8 MB/s eta 0:00:00
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting tinycss2
  Downloading tinycss2-1.3.0-py3-none-any.whl (22 kB)
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting jsonschema>=2.6
  Downloading jsonschema-4.22.0-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 281.3 MB/s eta 0:00:00
Collecting fastjsonschema
  Downloading fastjsonschema-2.19.1-py3-none-any.whl (23 kB)
Collecting tqdm>=4.32.2
  Downloading tqdm-4.66.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 272.2 MB/s eta 0:00:00
Requirement already satisfied: tenacity in /opt/app-root/lib/python3.9/site-packages (from papermill==2.3.4) (8.2.3)
Collecting ansiwrap
  Downloading ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting click
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 286.8 MB/s eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.9/738.9 kB 325.2 MB/s eta 0:00:00
Collecting wcwidth
  Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.3/142.3 kB 296.7 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.7-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 243.3 MB/s eta 0:00:00
Collecting parso<0.9.0,>=0.8.3
  Downloading parso-0.8.4-py2.py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.7/103.7 kB 268.2 MB/s eta 0:00:00
Collecting referencing>=0.28.4
  Downloading referencing-0.35.1-py3-none-any.whl (26 kB)
Collecting attrs>=22.2.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 245.0 MB/s eta 0:00:00
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.18.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 337.6 MB/s eta 0:00:00
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter-client==7.3.1) (1.16.0)
Collecting textwrap3>=0.9.2
  Downloading textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Downloading executing-2.0.1-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Downloading asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Installing collected packages: webencodings, wcwidth, textwrap3, pure-eval, ptyprocess, pickleshare, mistune, ipython-genutils, fastjsonschema, backcall, urllib3, traitlets, tqdm, tornado, tinycss2, soupsieve, rpds-py, pyzmq, pyyaml, pygments, psutil, prompt-toolkit, pexpect, parso, pandocfilters, nest-asyncio, MarkupSafe, lxml, jupyterlab-pygments, idna, executing, entrypoints, defusedxml, decorator, debugpy, click, charset-normalizer, certifi, bleach, attrs, asttokens, ansiwrap, stack-data, requests, referencing, minio, matplotlib-inline, jupyter-core, jinja2, jedi, beautifulsoup4, jupyter-client, jsonschema-specifications, ipython, jsonschema, ipykernel, nbformat, nbclient, papermill, nbconvert
Successfully installed MarkupSafe-2.1.1 ansiwrap-0.8.4 asttokens-2.4.1 attrs-23.2.0 backcall-0.2.0 beautifulsoup4-4.12.3 bleach-6.1.0 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 debugpy-1.8.1 decorator-5.1.1 defusedxml-0.7.1 entrypoints-0.4 executing-2.0.1 fastjsonschema-2.19.1 idna-3.7 ipykernel-6.13.0 ipython-8.10.0 ipython-genutils-0.2.0 jedi-0.19.1 jinja2-3.0.3 jsonschema-4.22.0 jsonschema-specifications-2023.12.1 jupyter-client-7.3.1 jupyter-core-4.11.2 jupyterlab-pygments-0.3.0 lxml-5.2.2 matplotlib-inline-0.1.7 minio-7.1.15 mistune-0.8.4 nbclient-0.6.3 nbconvert-6.5.1 nbformat-5.4.0 nest-asyncio-1.6.0 pandocfilters-1.5.1 papermill-2.3.4 parso-0.8.4 pexpect-4.9.0 pickleshare-0.7.5 prompt-toolkit-3.0.30 psutil-5.9.8 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.18.0 pyyaml-6.0.1 pyzmq-24.0.1 referencing-0.35.1 requests-2.31.0 rpds-py-0.18.1 soupsieve-2.5 stack-data-0.6.3 textwrap3-0.9.2 tinycss2-1.3.0 tornado-6.3.3 tqdm-4.66.4 traitlets-5.1.1 urllib3-1.26.9 wcwidth-0.2.13 webencodings-0.5.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
ansiwrap==0.8.4
asttokens==2.4.1
attrs==23.2.0
backcall==0.2.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.1.0
cycler==0.11.0
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==2.0.1
fastjsonschema==2.19.1
fonttools==4.42.0
idna==3.7
ipykernel==6.13.0
ipython==8.10.0
ipython-genutils==0.2.0
jedi==0.19.1
Jinja2==3.0.3
joblib==1.3.2
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter-client==7.3.1
jupyter_core==4.11.2
jupyterlab_pygments==0.3.0
kafka-python==2.0.2
kiwisolver==1.4.4
lxml==5.2.2
MarkupSafe==2.1.1
matplotlib==3.6.3
matplotlib-inline==0.1.7
micropipenv==1.5.0
minio==7.1.15
mistune==0.8.4
nbclient==0.6.3
nbconvert==6.5.1
nbformat==5.4.0
nest-asyncio==1.6.0
numpy==1.24.4
packaging==23.1
pandas==1.5.3
pandocfilters==1.5.1
papermill==2.3.4
parso==0.8.4
pexpect==4.9.0
pickleshare==0.7.5
Pillow==10.0.0
plotly==5.13.1
prompt-toolkit==3.0.30
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.18.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
pyzmq==24.0.1
referencing==0.35.1
requests==2.31.0
rpds-py==0.18.1
scikit-learn==1.2.2
scipy==1.10.1
six==1.16.0
soupsieve==2.5
stack-data==0.6.3
tenacity==8.2.3
textwrap3==0.9.2
threadpoolctl==3.2.0
tinycss2==1.3.0
toml==0.10.2
tornado==6.3.3
tqdm==4.66.4
traitlets==5.1.1
urllib3==1.26.9
wcwidth==0.2.13
webencodings==0.5.1
[I 09:28:21.724] 'sanity_check':'test_security' - Packages installed (12.913 secs)
[I 09:28:21.802] 'sanity_check':'test_security' - processing dependencies 
[D 09:28:21.802] Starting new HTTP connection (1): minio.ic-shared-minio.svc.cluster.local:9000
[D 09:28:21.812] http://minio.ic-shared-minio.svc.cluster.local:9000 "GET /user1?location= HTTP/1.1" 200 128
[D 09:28:21.814] http://minio.ic-shared-minio.svc.cluster.local:9000 "HEAD /user1/sanity_check-0531092802/test_security-6b595dc7-afb8-46bb-bf52-7cd695ddafb8.tar.gz HTTP/1.1" 200 0
[D 09:28:21.820] http://minio.ic-shared-minio.svc.cluster.local:9000 "GET /user1/sanity_check-0531092802/test_security-6b595dc7-afb8-46bb-bf52-7cd695ddafb8.tar.gz HTTP/1.1" 200 798
[I 09:28:21.821] 'sanity_check':'test_security' - downloaded test_security-6b595dc7-afb8-46bb-bf52-7cd695ddafb8.tar.gz from bucket: user1, object: sanity_check-0531092802/test_security-6b595dc7-afb8-46bb-bf52-7cd695ddafb8.tar.gz (0.019 secs)
tar: Removing leading `/' from member names
/
test_security.py
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
[I 09:28:21.831] 'sanity_check':'test_security' - dependencies processed (0.029 secs)
[I 09:28:21.831] 'sanity_check':'test_security' - executing python script using 'python3 test_security.py' to 'test_security.log' 
[E 09:28:21.964] Unexpected error: <class 'subprocess.CalledProcessError'>
[E 09:28:21.964] Error details: Command '['python3', 'test_security.py']' returned non-zero exit status 1.
[D 09:28:21.981] http://minio.ic-shared-minio.svc.cluster.local:9000 "PUT /user1/sanity_check-0531092802/test_security.log HTTP/1.1" 200 0
[I 09:28:21.982] 'sanity_check':'test_security' - uploaded test_security.log to bucket: user1 object: sanity_check-0531092802/test_security.log (0.017 secs)
Traceback (most recent call last):
  File "/opt/app-root/src/bootstrapper.py", line 747, in <module>
    main()
  File "/opt/app-root/src/bootstrapper.py", line 737, in main
    file_op.execute()
  File "/opt/app-root/src/bootstrapper.py", line 501, in execute
    raise ex
  File "/opt/app-root/src/bootstrapper.py", line 488, in execute
    subprocess.run(run_args, stdout=log_file, stderr=subprocess.STDOUT, check=True)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'test_security.py']' returned non-zero exit status 1.
```

**Comment by RHRolun** [comment]
Potential fix here: https://github.com/rh-aiservices-bu/insurance-claim-processing/tree/fix/3.6-sanity-check-fix
